include:
  - project: 'infrastructure/gitlab-ci'
    file: '/templates/maven/.maven-microservice-ci-full.yml'
    inputs:
      jdk_version: "21"
variables:
  KUBERNETES_MEMORY_REQUEST: "5Gi"
  KUBERNETES_MEMORY_LIMIT: "6Gi"
